sonar.projectKey=AreefShaik-prasthana_AI
sonar.organization=areefshaik-prasthana

sonar.sources=scientific_calculator/lib
sonar.tests=scientific_calculator/test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**

sonar.dart.lcov.reportPath=scientific_calculator/coverage/lcov.info
sonar.sourceEncoding=UTF-8