sonar.projectKey=AreefShaik-prasthana_AI
sonar.organization=areefshaik-prasthana
sonar.projectVersion=1.0.2

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*.dart
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**

sonar.dart.lcov.reportPath=coverage/lcov.info
sonar.sourceEncoding=UTF-8
