# sonar-project.properties
sonar.projectKey=AreefShaik-prasthana_AI
sonar.organization=areefshaik-prasthana

# Project source code paths
sonar.sources=lib
sonar.tests=test

# Coverage report path for Flutter
sonar.dart.lcov.reportPath=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
