sonar.projectKey=AreefShaik-prasthana_AI
sonar.organization=areefshaik-prasthana

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*.dart
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**

sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

# Dart-specific properties
sonar.dart.coverage.reportPaths=coverage/lcov.info
sonar.dart.tests.reportPaths=test
